### ISSUE TITLE
Green Art-ifacts on Payloads

### ISSUE THREAD

**Issue by alexgill** [merge/skulls#253] opened 2022-12-15 10:48 UTC
Hi. I noticed this after upgrading a couple of release back: 
When entering either 'nvramcui' or 'coreinfo', what's shown are green artifacts, the same _exact_ ones across two separate x230 laptops, so it's consistently problematic. Currently running the 1.0.6 release. I do notice a lot of battery drain when powered off, so maybe there's something related about things not being all right. Suggestions appreciated.

SCREENSHOTS:
[nvramcui](http://alexgill.com/IMG_20221214_180825.jpg)
[coreinfo](http://alexgill.com/IMG_20221214_180902.jpg)

**Comment by XRevan86** [comment] 2022-12-15 16:10
Duplicate of #231

**Comment by alexgill** [comment] 2022-12-15 16:44
Agreed, this is a dupclucate issue as pointed out. Thanks

**Closed** 2022-12-15 16:45 UTC
